global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'codelab-monitor'
rule_files:
scrape_configs:
   - job_name: 'prometheus'
     metrics_path: /metrics
     static_configs:
      - targets: ['csvserver:9300']
